name: Daily Scraper

on:
  schedule:
    - cron: '0 15 * * 0-4'

jobs:
  scrape_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Add requirements if needed

      - name: Run scrapper.py
        run: python scrapper.py
